### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Eshna0106** [cbyrohl/scida#167] opened 2024-07-08 12:31 UTC
The following code:

```
path_1=basepath+'TNG50-4'
ds_1=load(path_1)
snap_33=ds_1[33]
mask=snap_33.data["Subhalo"]["SubhaloGrNr"]==0
masses=snap_33.data["Subhalo"]["SubhaloMass"][mask]
most_massive_index=masses.argmax()
```
makes the following error message:

```
File ~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:342, in DaskMethodsMixin.compute(self, **kwargs)
    [318](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:318) def compute(self, **kwargs):
    [319](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:319)     """Compute this dask collection
    [320](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:320) 
    [321](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:321)     This turns a lazy Dask collection into its in-memory equivalent.
   (...)
    [340](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:340)     dask.compute
    [341](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:341)     """
--> [342](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:342)     (result,) = compute(self, traverse=False, **kwargs)
    [343](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:343)     return result

File ~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:628, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    [625](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:625)     postcomputes.append(x.__dask_postcompute__())
    [627](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:627) with shorten_traceback():
--> [628](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:628)     results = schedule(dsk, keys, **kwargs)
    [630](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/base.py:630) return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File ~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/array/reductions.py:1121, in arg_chunk(func, argfunc, x, axis, offset_info)
...
-> [1121](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/array/reductions.py:1121)     arg[:] = np.ravel_multi_index(total_ind, total_shape)
   [1122](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/array/reductions.py:1122) else:
   [1123](https://vscode-remote+ssh-002dremote-002bvera1.vscode-resource.vscode-cdn.net/u/esroy/~/.local/envs/lyman_alpha/lib/python3.9/site-packages/dask/array/reductions.py:1123)     arg += offset_info

TypeError: 'float' object cannot be interpreted as an integer
```
Is this a bug in scida or am I doing something wrong?

**Comment by cbyrohl** [comment] 2024-07-16 14:46
Thanks for the bug report. I cannot reproduce the issue when running:

```python
from scida import load

path_1='TNG50-4'
ds_1=load(path_1)
snap_33=ds_1[33]
mask=snap_33.data["Subhalo"]["SubhaloGrNr"]==0
masses=snap_33.data["Subhalo"]["SubhaloMass"][mask]
most_massive_index=masses.argmax()
```

Can you run this snippet again in a fresh session and post the following output?

``` python
import platform
from importlib.metadata import version
print("python version:", platform.python_version())
print("scida version:", version("scida"))
print("pint version:", version("pint"))
```

**Comment by dnelson86** [comment] 2024-08-15 11:30
Can reproduce with

```python
from scida import load

path_1='TNG50-4'
ds_1=load(path_1)
snap_33=ds_1[33]
mask=snap_33.data["Subhalo"]["SubhaloGrNr"]==0
masses=snap_33.data["Subhalo"]["SubhaloMass"][mask]
most_massive_index=masses.argmax()
most_massive_index.compute()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 most_massive_index.compute()

File ~/.local/envs/py312/lib/python3.12/site-packages/dask/base.py:376, in DaskMethodsMixin.compute(self, **kwargs)
    352 def compute(self, **kwargs):
    353     """Compute this dask collection
    354
    355     This turns a lazy Dask collection into its in-memory equivalent.
   (...)
    374     dask.compute
    375     """
--> 376     (result,) = compute(self, traverse=False, **kwargs)
    377     return result

File ~/.local/envs/py312/lib/python3.12/site-packages/dask/base.py:662, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    659     postcomputes.append(x.__dask_postcompute__())
    661 with shorten_traceback():
--> 662     results = schedule(dsk, keys, **kwargs)
    664 return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File ~/.local/envs/py312/lib/python3.12/site-packages/dask/array/reductions.py:1120, in arg_chunk(func, argfunc, x, axis, offset_info)
   1118     ind = np.unravel_index(arg.ravel()[0], x.shape)
   1119     total_ind = tuple(o + i for (o, i) in zip(offset, ind))
-> 1120     arg[:] = np.ravel_multi_index(total_ind, total_shape)
   1121 else:
   1122     arg += offset_info

TypeError: 'float' object cannot be interpreted as an integer
> /u/dnelson/.local/envs/py312/lib/python3.12/site-packages/dask/array/reductions.py(1120)arg_chunk()
   1118             ind = np.unravel_index(arg.ravel()[0], x.shape)
   1119             total_ind = tuple(o + i for (o, i) in zip(offset, ind))
-> 1120             arg[:] = np.ravel_multi_index(total_ind, total_shape)
   1121         else:
   1122             arg += offset_info
```

and

```
python version: 3.12.4
scida version: 0.3.2
pint version: 0.24.3
dask version: 2024.7.1
```

**Comment by cbyrohl** [comment] 2024-08-16 18:23
Thanks for the clarification. This appears to be unexpected behavior or a bug with dask. It occurs when first masking and subsequently searching for the argmax. A workaround in your specific case would be to convert the relatively small dask arrays into numpy arrays. I will raise the issue with the dask folks.

Minimal example:

``` python
    import dask.array as da
    import numpy as np
    float_arr = da.arange(1000, dtype=np.float32)
    idx = float_arr.argmax()
    idx = idx.compute()
    assert idx == 999
    mask = float_arr > 500
    float_arr_masked = float_arr[mask]
    idx = float_arr_masked.argmax()
    idx = idx.compute()
    assert idx == 999
```

Output:

```
test_issues.py:106: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.cache/pypoetry/virtualenvs/scida-dxVKvl_g-py3.10/lib/python3.10/site-packages/dask/base.py:342: in compute
    (result,) = compute(self, traverse=False, **kwargs)
../../../.cache/pypoetry/virtualenvs/scida-dxVKvl_g-py3.10/lib/python3.10/site-packages/dask/base.py:628: in compute
    results = schedule(dsk, keys, **kwargs)
../../../.cache/pypoetry/virtualenvs/scida-dxVKvl_g-py3.10/lib/python3.10/site-packages/dask/array/reductions.py:1121: in arg_chunk
    arg[:] = np.ravel_multi_index(total_ind, total_shape)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = ((498,), (nan,)), kwargs = {}, relevant_args = (498,)

>   ???
E   TypeError: 'float' object cannot be interpreted as an integer

<__array_function__ internals>:200: TypeError
```

with

python version: 3.10.10
dask version: 2023.12.1
numpy version: 1.24.4

and also with

python version: 3.12.4
dask version: 2024.7.1
numpy version: 1.26.4

**Comment by cbyrohl** [comment] 2024-08-21 17:45
Thinking about this more, not unlikely this is expected behavior for unknown shaped arrays. Particularly I wonder what the use case here might be here?

A likely workflow instead would be:

```python
import dask.array as da
import numpy as np
float_arr = da.arange(1000, dtype=np.float32)
idx = float_arr.argmax()
idx = idx.compute()
assert idx == 999
mask = da.where(float_arr > 500)[0].compute()
float_arr_masked = float_arr[mask]
idx = float_arr_masked.argmax()
idx = idx.compute()
assert idx == 498
```

In order to use this index, I would expect that the masked array, and thus the mask, would need to be computed, again. This snippet here also saves this second computation.

What do you think?

**Comment by dnelson86** [comment] 2024-08-23 14:52
@Eshna0106 can you confirm that changing the code, as above, would work for your use case? If so, we can close this issue.

**Comment by Eshna0106** [comment] 2024-11-17 19:20
I just checked, the above workflow works.

@cbyrohl the use case was that I was trying to compute the most massive subhalo of each group, compute their masses, find the most massive one amongst them, and compute the SubhaloSFRinHalfRad for that specific subhalo

**Comment by cbyrohl** [comment] 2024-12-16 17:51
Great to hear @Eshna0106 . Sorry that this is not exactly intuitive. As there's a workaround and this is probably dask related, I'll close this issue.

**Closed by cbyrohl** 2024-12-16 17:51 UTC
